### ISSUE TITLE
Server executable binaries are broken

### ISSUE THREAD

**Issue by sreejith-ms** [dmsl/anyplace#197]
Hi,
After the latest update of https://anyplace.cs.ucy.ac.cy/downloads/anyplace_v3.zip files, the bat file is not able to run.
Initially I'm getting the below exception when running on windows command prompt.
```
The input line is too long.
The syntax of the command is incorrect.
```
I fixed this issue by [adding a caret ^ symbol ](https://stackoverflow.com/a/69079)for new line.

```
set "APP_CLASSPATH=%APP_LIB_DIR%\..\conf;%APP_LIB_DIR%\anyplace_v3.anyplace_v3-0.5-sans-externalized.jar;%APP_LIB_DIR%\commons-codec-1.10.jar;%APP_LIB_DIR%\gson-2.2.4.jar;%APP_LIB_DIR%\Jama-1.0.2.jar;%APP_LIB_DIR%\jettison-1.1.jar;%APP_LIB_DIR%\JGoogleAnalyticsTracker-1.2.0.jar;%APP_LIB_DIR%\org.scala-lang.scala-library-2.11.7.jar;%APP_LIB_DIR%\com.typesafe.play.twirl-api_2.11-1.1.1.jar;%APP_LIB_DIR%\org.apache.commons.commons-lang3-3.4.jar;%APP_LIB_DIR%\org.scala-lang.modules.scala-xml_2.11-1.0.1.jar;%APP_LIB_DIR%\com.typesafe.play.play-server_2.11-2.4.2.jar;%APP_LIB_DIR%\com.typesafe.play.play_2.11-2.4.2.jar;%APP_LIB_DIR%\com.typesafe.play.build-link-2.4.2.jar;%APP_LIB_DIR%\com.typesafe.play.play-exceptions-2.4.2.jar;%APP_LIB_DIR%\org.javassist.javassist-3.19.0-GA.jar;%APP_LIB_DIR%\com.typesafe.play.play-iteratees_2.11-2.4.2.jar;%APP_LIB_DIR%\org.scala-stm.scala-stm_2.11-0.7.jar;%APP_LIB_DIR%\com.typesafe.config-1.3.0.jar;%APP_LIB_DIR%\com.typesafe.play.play-json_2.11-2.4.2.jar;%APP_LIB_DIR%\com.typesafe.play.play-functional_2.11-2.4.2.jar;%APP_LIB_DIR%\com.typesafe.play.play-datacommons_2.11-2.4.2.jar;%APP_LIB_DIR%\joda-time.joda-time-2.8.1.jar;%APP_LIB_DIR%\org.joda.joda-convert-1.7.jar;%APP_LIB_DIR%\com.fasterxml.jackson.core.jackson-core-2.5.4.jar;%APP_LIB_DIR%\com.fasterxml.jackson.core.jackson-annotations-2.5.4.jar;%APP_LIB_DIR%\com.fasterxml.jackson.core.jackson-databind-2.5.4.jar;%APP_LIB_DIR%\com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.5.4.jar;%APP_LIB_DIR%\com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.5.4.jar;%APP_LIB_DIR%\com.typesafe.play.play-netty-utils-2.4.2.jar;%APP_LIB_DIR%\org.slf4j.slf4j-api-1.7.12.jar;%APP_LIB_DIR%\org.slf4j.jul-to-slf4j-1.7.12.jar;%APP_LIB_DIR%\org.slf4j.jcl-over-slf4j-1.7.12.jar;%APP_LIB_DIR%\org.scala-lang.modules.scala-parser-combinators_2.11-1.0.1.jar;%APP_LIB_DIR%\ch.qos.logback.logback-core-1.1.3.jar;%APP_LIB_DIR%\ch.qos.logback.logback-classic-1.1.3.jar;%APP_LIB_DIR%\com.typesafe.akka.akka-actor_2.11-2.3.11.jar;%APP_LIB_DIR%\com.typesafe.akka.akka-slf4j_2.11-2.3.11.jar;%APP_LIB_DIR%\commons-codec.commons-codec-1.10.jar;%APP_LIB_DIR%\xerces.xercesImpl-2.11.0.jar;%APP_LIB_DIR%\xml-apis.xml-apis-1.4.01.jar;%APP_LIB_DIR%\javax.transaction.jta-1.1.jar;%APP_LIB_DIR%\com.google.inject.guice-4.0.jar;%APP_LIB_DIR%\javax.inject.javax.inject-1.jar;%APP_LIB_DIR%\aopalliance.aopalliance-1.0.jar;%APP_LIB_DIR%\com.google.inject.extensions.guice-assistedinject-4.0.jar;%APP_LIB_DIR%\com.typesafe.play.play-netty-server_2.11-2.4.2.jar;%APP_LIB_DIR%\io.netty.netty-3.10.3.Final.jar;%APP_LIB_DIR%\com.typesafe.netty.netty-http-pipelining-1.1.4.jar;%APP_LIB_DIR%\com.typesafe.play.play-jdbc_2.11-2.4.2.jar;%APP_LIB_DIR%\com.typesafe.play.play-jdbc-api_2.11-2.4.2.jar;%APP_LIB_DIR%\com.jolbox.bonecp-0.8.0.RELEASE.jar;%APP_LIB_DIR%\com.zaxxer.HikariCP-2.3.7.jar;%APP_LIB_DIR%\com.h2database.h2-1.4.187.jar;%APP_LIB_DIR%\tyrex.tyrex-1.0.1.jar;%APP_LIB_DIR%\com.typesafe.play.play-cache_2.11-2.4.2.jar;^
%APP_LIB_DIR%\net.sf.ehcache.ehcache-core-2.6.11.jar;%APP_LIB_DIR%\com.typesafe.play.play-ws_2.11-2.4.2.jar;%APP_LIB_DIR%\com.google.guava.guava-18.0.jar;%APP_LIB_DIR%\com.ning.async-http-client-1.9.21.jar;%APP_LIB_DIR%\oauth.signpost.signpost-core-1.2.1.2.jar;%APP_LIB_DIR%\oauth.signpost.signpost-commonshttp4-1.2.1.2.jar;%APP_LIB_DIR%\org.apache.httpcomponents.httpcore-4.0.1.jar;%APP_LIB_DIR%\org.apache.httpcomponents.httpclient-4.0.1.jar;%APP_LIB_DIR%\commons-logging.commons-logging-1.1.1.jar;%APP_LIB_DIR%\com.typesafe.play.filters-helpers_2.11-2.4.2.jar;%APP_LIB_DIR%\org.scalanlp.breeze_2.11-0.12.jar;%APP_LIB_DIR%\org.scalanlp.breeze-macros_2.11-0.12.jar;%APP_LIB_DIR%\org.scala-lang.scala-reflect-2.11.7.jar;%APP_LIB_DIR%\com.github.fommil.netlib.core-1.1.2.jar;%APP_LIB_DIR%\net.sourceforge.f2j.arpack_combined_all-0.1-javadoc.jar;%APP_LIB_DIR%\net.sourceforge.f2j.arpack_combined_all-0.1.jar;%APP_LIB_DIR%\net.sf.opencsv.opencsv-2.3.jar;%APP_LIB_DIR%\com.github.rwl.jtransforms-2.4.0.jar;%APP_LIB_DIR%\junit.junit-4.8.2.jar;%APP_LIB_DIR%\org.spire-math.spire_2.11-0.7.4.jar;%APP_LIB_DIR%\org.spire-math.spire-macros_2.11-0.7.4.jar;%APP_LIB_DIR%\com.chuusai.shapeless_2.11-2.0.0.jar;%APP_LIB_DIR%\org.scalanlp.breeze-natives_2.11-0.12.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_ref-osx-x86_64-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.native_ref-java-1.1.jar;%APP_LIB_DIR%\com.github.fommil.jniloader-1.1.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_ref-linux-x86_64-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_ref-linux-i686-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_ref-win-x86_64-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_ref-win-i686-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_ref-linux-armhf-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_system-osx-x86_64-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.native_system-java-1.1.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_system-linux-x86_64-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_system-linux-i686-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_system-linux-armhf-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_system-win-x86_64-1.1-natives.jar;%APP_LIB_DIR%\com.github.fommil.netlib.netlib-native_system-win-i686-1.1-natives.jar;%APP_LIB_DIR%\org.scalanlp.breeze-viz_2.11-0.12.jar;%APP_LIB_DIR%\jfree.jcommon-1.0.16.jar;%APP_LIB_DIR%\jfree.jfreechart-1.0.13.jar;%APP_LIB_DIR%\org.apache.xmlgraphics.xmlgraphics-commons-1.3.1.jar;%APP_LIB_DIR%\commons-io.commons-io-1.3.1.jar;%APP_LIB_DIR%\com.lowagie.itext-2.1.5.jar;%APP_LIB_DIR%\bouncycastle.bcmail-jdk14-138.jar;%APP_LIB_DIR%\bouncycastle.bcprov-jdk14-138.jar;%APP_LIB_DIR%\com.github.danielkorzekwa.bayes-scala-gp_2.11-0.1-SNAPSHOT.jar;%APP_LIB_DIR%\com.github.danielkorzekwa.bayes-scala_2.11-0.7-SNAPSHOT.jar;%APP_LIB_DIR%\org.apache.commons.commons-math3-3.3.jar;%APP_LIB_DIR%\com.typesafe.scala-logging.scala-logging-slf4j_2.11-2.1.2.jar;%APP_LIB_DIR%\com.typesafe.scala-logging.scala-logging-api_2.11-2.1.2.jar;%APP_LIB_DIR%\com.twitter.chill_2.11-0.8.0.jar;%APP_LIB_DIR%\com.twitter.chill-java-0.8.0.jar;%APP_LIB_DIR%\com.esotericsoftware.kryo-shaded-3.0.3.jar;%APP_LIB_DIR%\com.esotericsoftware.minlog-1.3.0.jar;%APP_LIB_DIR%\org.objenesis.objenesis-2.1.jar;%APP_LIB_DIR%\com.couchbase.client.java-client-2.4.5.jar;%APP_LIB_DIR%\com.couchbase.client.core-io-1.4.5.jar;%APP_LIB_DIR%\io.reactivex.rxjava-1.2.7.jar;%APP_LIB_DIR%\anyplace_v3.anyplace_v3-0.5-assets.jar"
```

Now I'm getting a new error.

```
[warn] application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
Oops, cannot start the server.
@771mipoh9: Cannot load module
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:131)
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:103)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at play.api.inject.Modules$.locate(Module.scala:103)
        at play.api.inject.guice.GuiceableModule$.loadModules(GuiceInjectorBuilder.scala:203)
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:22)
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:22)
        at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:79)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.ClassNotFoundException: play.filters.csrf.CSRFModule
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:105)
        ... 20 more
```

**Comment by sreejith-ms** [comment]
@Costantinos

**Comment by Costantinos** [comment]
Hello,

You can try running the server from a the path with a shorter name. You can do this by moving the anyplace folder to a directory with a shorter name or in "C://". Let me know if this solve the issue.

**Comment by sreejith-ms** [comment]
@Costantinos Yea, I already resolved that path issue. Now I'm stuck with the below error.

```
[warn] application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
Oops, cannot start the server.
@771mipoh9: Cannot load module
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:131)
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:103)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at play.api.inject.Modules$.locate(Module.scala:103)
        at play.api.inject.guice.GuiceableModule$.loadModules(GuiceInjectorBuilder.scala:203)
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:22)
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:22)
        at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:79)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.ClassNotFoundException: play.filters.csrf.CSRFModule
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:105)
        ... 20 more
```

**Comment by Costantinos** [comment]
Hello, 
I don't have any issue running the bat file on my windows machine. Did you move the server folder into a smaller directory? This may be related to windows path limit.

**Comment by sreejith-ms** [comment]
@Costantinos Thanks man, the issue is resolved when I moved to a short path 👍 
But now I'm getting an _NullPointerException_ when attempting to connect the two POIs, it is similar to #182 bug.

```
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.NullPointerException: null
        at db_models.Connection.getId(Connection.scala:96) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at controllers.AnyplaceMapping$$anonfun$connectionAdd$1.apply(AnyplaceMapping.scala:1317) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at controllers.AnyplaceMapping$$anonfun$connectionAdd$1.apply(AnyplaceMapping.scala:1278) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
[error] application -

! @7726319pf - Internal server error, for (POST) [/anyplace/mapping/connection/add] ->

play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.7.jar:na]
        at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
Caused by: java.lang.NullPointerException: null
        at db_models.Connection.getId(Connection.scala:96) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at controllers.AnyplaceMapping$$anonfun$connectionAdd$1.apply(AnyplaceMapping.scala:1317) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at controllers.AnyplaceMapping$$anonfun$connectionAdd$1.apply(AnyplaceMapping.scala:1278) ~[anyplace_v3.anyplace_v3-0.5-sans-externalized.jar:na]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
```

**Comment by Costantinos** [comment]
Hello,

We have updated the code and the binaries. You can try the latest version (many fixes have been applied).

**Comment by kapilsaini** [comment]
I am still facing  this issue. I did a clean build from develop branch. And it fails with exact same error message "The input line is too long.
The syntax of the command is incorrect."

I have my build directly under D: drive. Is there a possibe fix this , can any jars that are included be removed to shorten the classpath  ?
